apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-python-flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-python-flask-app
  template:
    metadata:
      labels:
        app: aks-python-flask-app
    spec:
      containers:
        - name: python-flask-app
          image: europenorthtestecr0001.azurecr.io/apps/python-flask-app
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
---
apiVersion: v1
kind: Service
metadata:
  name: aks-python-flask-app
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: aks-python-flask-app